"""Initial schema: accounts, transactions, postings, rates + starter chart.

Revision ID: 0001
Revises: (none)
Create Date: 2026-07-17

Hand-written (not autogenerated) because Alembic autogenerate cannot
guarantee TEXT storage for money columns.  Money amounts are stored as
string representations of Python ``Decimal`` values to avoid floating-point
precision loss.

All CHECK constraints are inlined in CREATE TABLE because SQLite does
not support ``ALTER TABLE … ADD CONSTRAINT``.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ── Tables ───────────────────────────────────────────────────────────────────


def _create_accounts() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS accounts (
            id          INTEGER   PRIMARY KEY AUTOINCREMENT,
            name        TEXT      NOT NULL UNIQUE COLLATE NOCASE,
            parent_id   INTEGER   REFERENCES accounts(id) ON DELETE RESTRICT,
            currency    TEXT      NOT NULL DEFAULT 'COP'
                                  CHECK(currency IN ('COP','USD','EUR','GBP','JPY')),
            depth       INTEGER   NOT NULL DEFAULT 0
                                  CHECK(depth >= 0 AND depth <= 2),
            kind        TEXT      NOT NULL
                                  CHECK(kind IN ('Assets','Liabilities','Equity','Income','Expenses')),
            is_archived INTEGER   NOT NULL DEFAULT 0
                                  CHECK(is_archived IN (0,1)),
            created_at  TEXT      NOT NULL DEFAULT (date('now'))
        )
        """
    )
    op.create_index("idx_accounts_parent", "accounts", ["parent_id"])
    op.create_index("idx_accounts_kind", "accounts", ["kind"])


def _create_transactions() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS transactions (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            date        TEXT    NOT NULL CHECK(date IS date(date)),
            description TEXT    NOT NULL DEFAULT '' CHECK(length(description) <= 256),
            created_at  TEXT    NOT NULL DEFAULT (date('now'))
        )
        """
    )
    op.create_index("idx_transactions_date", "transactions", ["date"])


def _create_postings() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS postings (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            transaction_id  INTEGER NOT NULL REFERENCES transactions(id) ON DELETE RESTRICT,
            account_id      INTEGER NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,
            amount          TEXT    NOT NULL CHECK(amount != '0'),
            currency        TEXT    NOT NULL DEFAULT 'COP',
            UNIQUE(transaction_id, account_id)
        )
        """
    )
    op.create_index("idx_postings_account", "postings", ["account_id"])
    op.create_index("idx_postings_transaction", "postings", ["transaction_id"])
    op.create_index(
        "idx_postings_account_date",
        "postings",
        ["account_id", "transaction_id"],
    )


def _create_rates() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS rates (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            base_currency   TEXT    NOT NULL,
            target_currency TEXT    NOT NULL,
            rate            TEXT    NOT NULL,
            date            TEXT    NOT NULL,
            source          TEXT    NOT NULL DEFAULT 'Frankfurter',
            UNIQUE(base_currency, target_currency, date)
        )
        """
    )


# ── Starter chart data ───────────────────────────────────────────────────────


STARTER_ACCOUNTS: list[dict[str, str | int]] = [
    {"name": "Assets:Checking", "currency": "COP", "depth": 1, "kind": "Assets"},
    {"name": "Assets:Savings", "currency": "COP", "depth": 1, "kind": "Assets"},
    {"name": "Assets:Cash", "currency": "COP", "depth": 1, "kind": "Assets"},
    {"name": "Liabilities:CreditCard", "currency": "COP", "depth": 1, "kind": "Liabilities"},
    {"name": "Equity:OpeningBalances", "currency": "COP", "depth": 1, "kind": "Equity"},
    {"name": "Income:Salary", "currency": "COP", "depth": 1, "kind": "Income"},
    {"name": "Expenses:Food:Groceries", "currency": "COP", "depth": 2, "kind": "Expenses"},
    {"name": "Expenses:Food:Restaurants", "currency": "COP", "depth": 2, "kind": "Expenses"},
    {"name": "Expenses:Rent", "currency": "COP", "depth": 1, "kind": "Expenses"},
    {"name": "Expenses:Transport", "currency": "COP", "depth": 1, "kind": "Expenses"},
    {"name": "Expenses:Subscriptions", "currency": "COP", "depth": 1, "kind": "Expenses"},
]


def _seed_starter_chart() -> None:
    """Insert the 11-account starter chart using INSERT OR IGNORE."""
    for acct in STARTER_ACCOUNTS:
        op.execute(
            sa.text(
                """INSERT OR IGNORE INTO accounts (name, currency, depth, kind)
                   VALUES (:name, :currency, :depth, :kind)"""
            ).bindparams(**acct)
        )


# ── Migration entry points ───────────────────────────────────────────────────


def upgrade() -> None:
    _create_accounts()
    _create_transactions()
    _create_postings()
    _create_rates()
    _seed_starter_chart()


def downgrade() -> None:
    op.drop_table("rates")
    op.drop_table("postings")
    op.drop_table("transactions")
    op.drop_table("accounts")
