"""Multi-currency schema: transactions.currency, rates.fetched_at, widen accounts CHECK.

- Add transactions.currency + backfill from dominant posting currency (B4)
- Add rates.fetched_at TTL column + idx_rates_lookup (FX-1)
- Widen accounts.currency CHECK from 5 to 12 currencies (B3)

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-18

Hand-written (not autogenerated).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from pyfintracker.validation import PER_CURRENCY_DECIMALS

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ── Transactions.currency ──────────────────────────────────────────────────────


def _add_transactions_currency() -> None:
    """Add currency column to transactions with default and backfill."""
    op.add_column(
        "transactions",
        sa.Column("currency", sa.Text(), nullable=False, server_default="COP"),
    )
    # Backfill from dominant posting currency (most common currency among postings)
    op.execute(
        """
        UPDATE transactions
        SET currency = (
            SELECT p.currency FROM postings p
            WHERE p.transaction_id = transactions.id
            GROUP BY p.currency
            ORDER BY COUNT(*) DESC
            LIMIT 1
        )
        """
    )
    op.create_index("idx_transactions_currency", "transactions", ["currency"])


def _remove_transactions_currency() -> None:
    """Reverse: drop currency column and index."""
    op.drop_index("idx_transactions_currency", table_name="transactions")
    op.drop_column("transactions", "currency")


# ── Rates.fetched_at + index ──────────────────────────────────────────────────


def _add_rates_fetched_at() -> None:
    """Add fetched_at column and lookup index."""
    op.add_column(
        "rates",
        sa.Column(
            "fetched_at",
            sa.Text(),
            nullable=False,
            server_default=sa.text("(datetime('now'))"),
        ),
    )
    op.create_index(
        "idx_rates_lookup",
        "rates",
        ["base_currency", "target_currency", "date"],
    )


def _remove_rates_fetched_at() -> None:
    """Reverse: drop column and index."""
    op.drop_index("idx_rates_lookup", table_name="rates")
    op.drop_column("rates", "fetched_at")


# ── Widen accounts.currency CHECK (SQLite recreate-table dance) ────────────────


ALLOWED_CURRENCIES_12 = ",".join(f"'{c}'" for c in PER_CURRENCY_DECIMALS)
ALLOWED_CURRENCIES_5 = "'COP','USD','EUR','GBP','JPY'"


def _widen_accounts_check() -> None:
    """Recreate accounts table with 12-currency CHECK constraint.

    SQLite does not support ALTER TABLE … ALTER CONSTRAINT, so we must
    recreate the table, copy data, drop the old, and rename the new.
    """
    op.execute(
        f"""
        CREATE TABLE accounts_new (
            id          INTEGER   PRIMARY KEY AUTOINCREMENT,
            name        TEXT      NOT NULL UNIQUE COLLATE NOCASE,
            parent_id   INTEGER   REFERENCES accounts(id) ON DELETE RESTRICT,
            currency    TEXT      NOT NULL DEFAULT 'COP'
                                  CHECK(currency IN ({ALLOWED_CURRENCIES_12})),
            depth       INTEGER   NOT NULL DEFAULT 0
                                  CHECK(depth >= 0 AND depth <= 2),
            kind        TEXT      NOT NULL
                                  CHECK(kind IN ('Assets','Liabilities','Equity','Income','Expenses')),
            is_archived INTEGER   NOT NULL DEFAULT 0
                                  CHECK(is_archived IN (0,1)),
            created_at  TEXT      NOT NULL DEFAULT (date('now'))
        )
        """
    )
    op.execute("INSERT INTO accounts_new SELECT * FROM accounts")
    op.execute("DROP TABLE accounts")
    op.execute("ALTER TABLE accounts_new RENAME TO accounts")
    op.create_index("idx_accounts_parent", "accounts", ["parent_id"])
    op.create_index("idx_accounts_kind", "accounts", ["kind"])


def _narrow_accounts_check() -> None:
    """Restore 5-currency CHECK constraint (downgrade)."""
    op.execute(
        f"""
        CREATE TABLE accounts_old (
            id          INTEGER   PRIMARY KEY AUTOINCREMENT,
            name        TEXT      NOT NULL UNIQUE COLLATE NOCASE,
            parent_id   INTEGER   REFERENCES accounts(id) ON DELETE RESTRICT,
            currency    TEXT      NOT NULL DEFAULT 'COP'
                                  CHECK(currency IN ({ALLOWED_CURRENCIES_5})),
            depth       INTEGER   NOT NULL DEFAULT 0
                                  CHECK(depth >= 0 AND depth <= 2),
            kind        TEXT      NOT NULL
                                  CHECK(kind IN ('Assets','Liabilities','Equity','Income','Expenses')),
            is_archived INTEGER   NOT NULL DEFAULT 0
                                  CHECK(is_archived IN (0,1)),
            created_at  TEXT      NOT NULL DEFAULT (date('now'))
        )
        """
    )
    op.execute("INSERT INTO accounts_old SELECT * FROM accounts")
    op.execute("DROP TABLE accounts")
    op.execute("ALTER TABLE accounts_old RENAME TO accounts")
    op.create_index("idx_accounts_parent", "accounts", ["parent_id"])
    op.create_index("idx_accounts_kind", "accounts", ["kind"])


# ── Migration entry points ───────────────────────────────────────────────────


def upgrade() -> None:
    _add_transactions_currency()
    _add_rates_fetched_at()
    _widen_accounts_check()


def downgrade() -> None:
    _narrow_accounts_check()
    _remove_rates_fetched_at()
    _remove_transactions_currency()
