"""Tags: tags + transaction_tags tables for categorising transactions.

- Creates `tags` table (id, name, account_id, created_at)
- Creates `transaction_tags` join table (transaction_id, tag_id)
- Two partial unique indexes instead of UNIQUE(name, account_id) because
  SQLite UNIQUE treats NULL != NULL (allows duplicate global tags).

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-20

Hand-written (not autogenerated).
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    _ = revision, down_revision, branch_labels, depends_on  # alembic reads globals via reflection
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS tags (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            name        TEXT    NOT NULL,
            account_id  INTEGER REFERENCES accounts(id) ON DELETE CASCADE,
            created_at  TEXT    NOT NULL DEFAULT (date('now'))
        )
        """
    )
    op.execute(
        "CREATE UNIQUE INDEX idx_tags_name_global ON tags(name) WHERE account_id IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX idx_tags_name_account ON tags(name, account_id) WHERE account_id IS NOT NULL"
    )
    op.create_index("idx_tags_account", "tags", ["account_id"])

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS transaction_tags (
            transaction_id INTEGER NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
            tag_id         INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
            PRIMARY KEY (transaction_id, tag_id)
        )
        """
    )
    op.create_index("idx_transaction_tags_txn", "transaction_tags", ["transaction_id"])
    op.create_index("idx_transaction_tags_tag", "transaction_tags", ["tag_id"])


def downgrade() -> None:
    op.drop_table("transaction_tags")
    op.drop_table("tags")
