"""FTS5 full-text search virtual table for transactions.description.

- Creates ``transactions_fts`` FTS5 virtual table on description
- Sync triggers: AFTER INSERT / DELETE / UPDATE on transactions

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-20

Hand-written (not autogenerated).
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    _ = revision, down_revision, branch_labels, depends_on  # alembic reads globals via reflection
    op.execute(
        """
        CREATE VIRTUAL TABLE transactions_fts USING fts5(
            description,
            content='transactions',
            content_rowid='id'
        )
        """
    )
    op.execute(
        """
        CREATE TRIGGER transactions_ai AFTER INSERT ON transactions BEGIN
            INSERT INTO transactions_fts(rowid, description) VALUES (new.id, new.description);
        END;
        """
    )
    op.execute(
        """
        CREATE TRIGGER transactions_ad AFTER DELETE ON transactions BEGIN
            INSERT INTO transactions_fts(transactions_fts, rowid, description)
            VALUES('delete', old.id, old.description);
        END;
        """
    )
    op.execute(
        """
        CREATE TRIGGER transactions_au AFTER UPDATE ON transactions BEGIN
            INSERT INTO transactions_fts(transactions_fts, rowid, description)
            VALUES('delete', old.id, old.description);
            INSERT INTO transactions_fts(rowid, description) VALUES (new.id, new.description);
        END;
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS transactions_ai")
    op.execute("DROP TRIGGER IF EXISTS transactions_ad")
    op.execute("DROP TRIGGER IF EXISTS transactions_au")
    op.execute("DROP TABLE IF EXISTS transactions_fts")
