"""Recurring transaction rules table.

- ``recurring_rules`` — defines a recurring schedule for generating transactions
- ``recurring_postings`` — posting templates for each recurring rule

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-20

Hand-written (not autogenerated).
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _create_recurring_rules() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS recurring_rules (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            name        TEXT    NOT NULL,
            description TEXT    NOT NULL DEFAULT '',
            frequency   TEXT    NOT NULL DEFAULT 'monthly'
                              CHECK(frequency IN ('daily','weekly','monthly','yearly')),
            interval_days INTEGER NOT NULL DEFAULT 0,
            day_of_month INTEGER,
            day_of_week  INTEGER,
            start_date  TEXT    NOT NULL CHECK(start_date IS date(start_date)),
            end_date    TEXT    CHECK(end_date IS date(end_date)),
            next_date   TEXT    NOT NULL CHECK(next_date IS date(next_date)),
            is_active   INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0,1)),
            created_at  TEXT    NOT NULL DEFAULT (date('now'))
        )
        """
    )


def _create_recurring_postings() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS recurring_postings (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            rule_id     INTEGER NOT NULL REFERENCES recurring_rules(id) ON DELETE CASCADE,
            account_id  INTEGER NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,
            amount      TEXT    NOT NULL CHECK(amount != '0'),
            currency    TEXT    NOT NULL DEFAULT 'COP'
        )
        """
    )
    op.create_index("idx_recurring_postings_rule", "recurring_postings", ["rule_id"])


def upgrade() -> None:
    _create_recurring_rules()
    _create_recurring_postings()


def downgrade() -> None:
    op.drop_table("recurring_postings")
    op.drop_table("recurring_rules")
