"""Budget tracking tables.

- ``budgets`` — defines spending budgets with period, scope, and limit.

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-20

Hand-written (not autogenerated).
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    _ = revision, down_revision, branch_labels, depends_on  # alembic reads globals via reflection
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS budgets (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            name        TEXT    NOT NULL,
            amount      TEXT    NOT NULL,
            currency    TEXT    NOT NULL DEFAULT 'COP',
            period      TEXT    NOT NULL CHECK(period IN ('monthly','yearly')),
            account_id  INTEGER REFERENCES accounts(id) ON DELETE SET NULL,
            tag_id      INTEGER REFERENCES tags(id) ON DELETE SET NULL,
            start_date  TEXT    NOT NULL,
            is_active   INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0,1)),
            created_at  TEXT    NOT NULL DEFAULT (date('now'))
        )
        """
    )


def downgrade() -> None:
    op.drop_table("budgets")
